package tms.backend.domain;

// Generated Sep 12, 2013 8:08:12 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssetCategory generated by hbm2java
 */
@Entity
@Table(name = "asset_category")
public class AssetCategory implements java.io.Serializable {

	private Long id;
	private String categoryName;
	private Long departmentId;

	public AssetCategory() {
	}

	public AssetCategory(String categoryName, Long departmentId) {
		this.categoryName = categoryName;
		this.departmentId = departmentId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "category_name", length = 50)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "department_id")
	public Long getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Long departmentId) {
		this.departmentId = departmentId;
	}

}
