package tms.backend.domain;

// Generated Sep 12, 2013 8:08:12 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Asset generated by hbm2java
 */
@Entity
@Table(name = "asset_permission")
public class AssetPermission implements java.io.Serializable {

	private Long id;
	private Long userId;
	private String userName;
	private Long organizationId;
	private Byte permissionId;
	private String permissionName;
	

	public AssetPermission() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "userId")
	public Long getUserId() {
		return userId;
	}


	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "organizationId")
	public Long getOrganizationId() {
		return organizationId;
	}


	public void setOrganizationId(Long organizationId) {
		this.organizationId = organizationId;
	}

	@Column(name = "permissionId")
	public Byte getPermissionId() {
		return permissionId;
	}


	public void setPermissionId(Byte permissionId) {
		this.permissionId = permissionId;
	}

	@Column(name = "userName")
	public String getUserName() {
		return userName;
	}


	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "permissionName")
	public String getPermissionName() {
		return permissionName;
	}


	public void setPermissionName(String permissionName) {
		this.permissionName = permissionName;
	}

}
