package tms.backend.domain;

// Generated Sep 12, 2013 8:08:12 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssetCategory generated by hbm2java
 */
@Entity
@Table(name = "asset_location")
public class AssetLocation implements java.io.Serializable {

	private Long id;
	private String locationCode;
	private String locationName;

	public AssetLocation() {
	}

	public AssetLocation(String locationCode, String locationName) {
		this.locationCode = locationCode;
		this.locationName = locationName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "location_code", length = 50)
	public String getLocationCode() {
		return this.locationCode;
	}

	public void setLocationCode(String locationCode) {
		this.locationCode = locationCode;
	}

	@Column(name = "location_name")
	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

}
