package tms.backend.domain;

// Generated Sep 12, 2013 8:08:12 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AssetHistory generated by hbm2java
 */
@Entity
@Table(name = "asset_history")
public class AssetHistory implements java.io.Serializable {

	private Long id;
	private Long assetId;
	private String description;
	private Date startDate;
	private Date endDate;
	private Byte transType;
	private Date transDate;
	private String employee;
	private String employeeCode;
	private String department;
	private Integer userId;
	private String memo;
	private String createdBy;
	private Date createdDate;
	private Byte actionStatus;
	private String actionBy;
	private Date actionDate;
	private String locationCode;
	public AssetHistory() {
	}

	public AssetHistory(Long assetId, String description, Date startDate,
			Date endDate, Byte transType, String employee, Integer userId,
			String memo) {
		this.assetId = assetId;
		this.description = description;
		this.startDate = startDate;
		this.endDate = endDate;
		this.transType = transType;
		this.employee = employee;
		this.userId = userId;
		this.memo = memo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "asset_id")
	public Long getAssetId() {
		return this.assetId;
	}

	public void setAssetId(Long assetId) {
		this.assetId = assetId;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 0)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 0)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "trans_type")
	public Byte getTransType() {
		return this.transType;
	}

	public void setTransType(Byte transType) {
		this.transType = transType;
	}

	@Column(name = "employee")
	public String getEmployee() {
		return this.employee;
	}

	public void setEmployee(String employee) {
		this.employee = employee;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "memo")
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "trans_date", length = 0)
	public Date getTransDate() {
		return transDate;
	}

	public void setTransDate(Date transDate) {
		this.transDate = transDate;
	}

	/**
	 * @return the createdBy
	 */
	@Column(name = "created_by")
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * @param createdBy the createdBy to set
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * @return the createdDate
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 0)
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * @return the actionBy
	 */
	@Column(name = "action_by")
	public String getActionBy() {
		return actionBy;
	}

	/**
	 * @param actionBy the actionBy to set
	 */
	public void setActionBy(String actionBy) {
		this.actionBy = actionBy;
	}

	/**
	 * @return the actionDate
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "action_date", length = 0)
	public Date getActionDate() {
		return actionDate;
	}

	/**
	 * @param actionDate the actionDate to set
	 */
	public void setActionDate(Date actionDate) {
		this.actionDate = actionDate;
	}

	/**
	 * @return the actionStatus
	 */
	@Column(name = "action_status")
	public Byte getActionStatus() {
		return actionStatus;
	}

	/**
	 * @param actionStatus the actionStatus to set
	 */
	public void setActionStatus(Byte actionStatus) {
		this.actionStatus = actionStatus;
	}

	/**
	 * @return the employeeCode
	 */
	@Column(name = "employee_no")
	public String getEmployeeCode() {
		return employeeCode;
	}

	/**
	 * @param employeeCode the employeeCode to set
	 */
	public void setEmployeeCode(String employeeCode) {
		this.employeeCode = employeeCode;
	}

	/**
	 * @return the department
	 */
	@Column(name = "department")
	public String getDepartment() {
		return department;
	}

	/**
	 * @param department the department to set
	 */
	public void setDepartment(String department) {
		this.department = department;
	}
	@Column(name = "location_code", length = 50)
	public String getLocationCode() {
		return this.locationCode;
	}

	public void setLocationCode(String locationCode) {
		this.locationCode = locationCode;
	}


}
