package tms.backend.domain;

// Generated Sep 12, 2013 8:08:12 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Asset generated by hbm2java
 */
@Entity
@Table(name = "asset")
public class Asset implements java.io.Serializable {

	private Long id;
	private Long parentId;
	private Byte leaf;
	private String code;
	private String name;
	private String serial;
	private String manufacturer;
	private String model;
	private String distributor;
	private String store;
	private String storeAddress;
	private String description;
	private Date purchasedDate;
	private Date expiredDate;
	private String warranty;
	private Byte status;
	private Date updatedDate;
//	private Long categoryId;
	private AssetCategory category;
	private String employee;
	private String employeeCode;
	private String department;
	private String locationCode;
	private String owner;
	private Byte requestType;
	public Asset() {
	}

	public Asset(String name, String serial, String manufacturer,
			String distributor, String store, String storeAddress,
			String description, Date purchasedDate, Date expiredDate,
			String warranty, Byte status, Long categoryId) {
		this.name = name;
		this.serial = serial;
		this.manufacturer = manufacturer;
		this.distributor = distributor;
		this.store = store;
		this.storeAddress = storeAddress;
		this.description = description;
		this.purchasedDate = purchasedDate;
		this.expiredDate = expiredDate;
		this.warranty = warranty;
		this.status = status;
//		this.categoryId = categoryId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@Column(name = "parentId")
	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}
	@Column(name = "leaf")
	public Byte getLeaf() {
		return this.leaf;
	}

	public void setLeaf(Byte leaf) {
		this.leaf = leaf;
	}
	@Column(name = "code", length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "serial", length = 20)
	public String getSerial() {
		return this.serial;
	}

	public void setSerial(String serial) {
		this.serial = serial;
	}

	@Column(name = "manufacturer", length = 50)
	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Column(name = "distributor", length = 50)
	public String getDistributor() {
		return this.distributor;
	}

	public void setDistributor(String distributor) {
		this.distributor = distributor;
	}

	@Column(name = "store", length = 50)
	public String getStore() {
		return this.store;
	}

	public void setStore(String store) {
		this.store = store;
	}

	@Column(name = "storeAddress", columnDefinition="TEXT")
	public String getStoreAddress() {
		return this.storeAddress;
	}

	public void setStoreAddress(String storeAddress) {
		this.storeAddress = storeAddress;
	}

	@Column(name = "description", columnDefinition="TEXT")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "purchasedDate", length = 0)
	public Date getPurchasedDate() {
		return this.purchasedDate;
	}

	public void setPurchasedDate(Date purchasedDate) {
		this.purchasedDate = purchasedDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expiredDate", length = 0)
	public Date getExpiredDate() {
		return this.expiredDate;
	}

	public void setExpiredDate(Date expiredDate) {
		this.expiredDate = expiredDate;
	}

	@Column(name = "warranty")
	public String getWarranty() {
		return this.warranty;
	}

	public void setWarranty(String warranty) {
		this.warranty = warranty;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

//	@Column(name = "category_id")
//	public Long getCategoryId() {
//		return this.categoryId;
//	}
//
//	public void setCategoryId(Long categoryId) {
//		this.categoryId = categoryId;
//	}
	@ManyToOne
	@JoinColumn(name = "categoryId")
	public AssetCategory getCategory() {
		return category;
	}

	public void setCategory(AssetCategory category) {
		this.category = category;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "updatedDate", length = 0)
	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	@Column(name = "employee")
	public String getEmployee() {
		return this.employee;
	}

	public void setEmployee(String employee) {
		this.employee = employee;
	}
	/**
	 * @return the employeeCode
	 */
	@Column(name = "employeeNo",  length = 50)
	public String getEmployeeCode() {
		return employeeCode;
	}

	/**
	 * @param employeeCode the employeeCode to set
	 */
	public void setEmployeeCode(String employeeCode) {
		this.employeeCode = employeeCode;
	}

	/**
	 * @return the department
	 */
	@Column(name = "department", length = 50)
	public String getDepartment() {
		return department;
	}

	/**
	 * @param department the department to set
	 */
	public void setDepartment(String department) {
		this.department = department;
	}

	/**
	 * @return the model
	 */
	@Column(name = "model", length = 255)
	public String getModel() {
		return model;
	}

	/**
	 * @param model the model to set
	 */
	public void setModel(String model) {
		this.model = model;
	}
	@Column(name = "locationCode", length = 50)
	public String getLocationCode() {
		return this.locationCode;
	}

	public void setLocationCode(String locationCode) {
		this.locationCode = locationCode;
	}

	/**
	 * @return the owner
	 */
	@Column(name = "owner", length = 50)
	public String getOwner() {
		return owner;
	}

	/**
	 * @param owner the owner to set
	 */
	public void setOwner(String owner) {
		this.owner = owner;
	}

	/**
	 * @return the requestType
	 */
	@Column(name = "requestType")
	public Byte getRequestType() {
		return requestType;
	}

	/**
	 * @param requestType the requestType to set
	 */
	public void setRequestType(Byte requestType) {
		this.requestType = requestType;
	}

}
