package tms.backend.domain;

// Generated Jun 11, 2014 11:25:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssyProductDefect generated by hbm2java
 */
@Entity
@Table(name = "assy_product_defect")
public class AssyProductDefect implements java.io.Serializable {

	private Long id;
	private String defectCode;
	private String defectNameEn;
	private String defectNameVn;
	private Byte status;

	public AssyProductDefect() {
	}

	public AssyProductDefect(String defectNameVn) {
		this.defectNameVn = defectNameVn;
	}

	public AssyProductDefect(String defectCode,
			String defectNameEn, String defectNameVn, Byte status) {
		this.defectCode = defectCode;
		this.defectNameEn = defectNameEn;
		this.defectNameVn = defectNameVn;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "defect_code", length = 20)
	public String getDefectCode() {
		return this.defectCode;
	}

	public void setDefectCode(String defectCode) {
		this.defectCode = defectCode;
	}

	@Column(name = "defect_name_en", columnDefinition="TEXT")
	public String getDefectNameEn() {
		return this.defectNameEn;
	}

	public void setDefectNameEn(String defectNameEn) {
		this.defectNameEn = defectNameEn;
	}

	@Column(name = "defect_name_vn", nullable = false, columnDefinition="TEXT")
	public String getDefectNameVn() {
		return this.defectNameVn;
	}

	public void setDefectNameVn(String defectNameVn) {
		this.defectNameVn = defectNameVn;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
