package tms.backend.domain;

// Generated Jun 11, 2014 11:25:07 AM by Hibernate Tools 3.4.0.CR1

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * AssyProductTest generated by hbm2java
 */
@Entity
@Table(name = "assy_product_test")
public class AssyProductTest implements java.io.Serializable {

	private Long id;
	private Long productType;
	private Long productModel;
	private Date datetimetested;
	private String operator;
	private Byte status;
	private String sessionId;
	private String defectcode;
	private String serial;
	private String paramData;
	private Long station;
	private String stationName;
	private Integer stationStep;
	private Long reworkid;
	private Long prerequisiteId;
	@Transient
	private String prerequisiteData;

	public AssyProductTest() {
	}

	public AssyProductTest(Long productModel, Date datetimetested,
			String operator, Byte status, String sessionId, String defectcode,
			String serial, String paramData, Long station, String stationName,
			Integer stationStep, Long reworkid) {
		this.productModel = productModel;
		this.datetimetested = datetimetested;
		this.operator = operator;
		this.status = status;
		this.sessionId = sessionId;
		this.defectcode = defectcode;
		this.serial = serial;
		this.paramData = paramData;
		this.station = station;
		this.stationName = stationName;
		this.stationStep = stationStep;
		this.reworkid = reworkid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@Column(name = "product_type")
	public Long getProductType() {
		return productType;
	}

	public void setProductType(Long productType) {
		this.productType = productType;
	}
	
	@Column(name = "product_model")
	public Long getProductModel() {
		return this.productModel;
	}

	public void setProductModel(Long productModel) {
		this.productModel = productModel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetimetested", length = 0)
	public Date getDatetimetested() {
		return this.datetimetested;
	}

	public void setDatetimetested(Date datetimetested) {
		this.datetimetested = datetimetested;
	}

	@Column(name = "operator")
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "sessionId", length = 255)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name = "defectcode", length = 20)
	public String getDefectcode() {
		return this.defectcode;
	}

	public void setDefectcode(String defectcode) {
		this.defectcode = defectcode;
	}

	@Column(name = "serial", length = 20)
	public String getSerial() {
		return this.serial;
	}

	public void setSerial(String serial) {
		this.serial = serial;
	}

	@Column(name = "param_data", columnDefinition="TEXT")
	public String getParamData() {
		return this.paramData;
	}

	public void setParamData(String paramData) {
		this.paramData = paramData;
	}

	@Column(name = "station")
	public Long getStation() {
		return this.station;
	}

	public void setStation(Long station) {
		this.station = station;
	}

	@Column(name = "station_name", columnDefinition="TEXT")
	public String getStationName() {
		return this.stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	@Column(name = "station_step")
	public Integer getStationStep() {
		return this.stationStep;
	}

	public void setStationStep(Integer stationStep) {
		this.stationStep = stationStep;
	}

	@Column(name = "reworkid")
	public Long getReworkid() {
		return this.reworkid;
	}

	public void setReworkid(Long reworkid) {
		this.reworkid = reworkid;
	}
	@Column(name = "prequisitionId")
	public Long getPrerequisiteId() {
		return prerequisiteId;
	}

	public void setPrerequisiteId(Long prerequisiteId) {
		this.prerequisiteId = prerequisiteId;
	}
	@Transient
	public String getPrerequisiteData() {
		return prerequisiteData;
	}

	public void setPrerequisiteData(String prerequisiteData) {
		this.prerequisiteData = prerequisiteData;
	}
	
	

}
