package tms.backend.domain;

// Generated Jun 11, 2014 11:25:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssyProductModel generated by hbm2java
 */
@Entity
@Table(name = "assy_product_model")
public class AssyProductModel implements java.io.Serializable, Comparable<AssyProductModel> {

	private Long id;
	private String productModel;
	private Byte status;
	private Long productType;
	private String productModelName;
	private String validateFnOnClient;
	private String validateFnOnServer;
	private Boolean allowDuplicate;
	public AssyProductModel() {
	}

	public AssyProductModel(String productName, Byte status, Long productType,
			String productModelName) {
		this.productModel = productModel;
		this.status = status;
		this.productType = productType;
		this.productModelName = productModelName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "product_model")
	public String getProductModel() {
		return this.productModel;
	}

	public void setProductModel(String productModel) {
		this.productModel = productModel;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "product_type")
	public Long getProductType() {
		return this.productType;
	}

	public void setProductType(Long productType) {
		this.productType = productType;
	}

	@Column(name = "product_model_name")
	public String getProductModelName() {
		return this.productModelName;
	}

	public void setProductModelName(String productModelName) {
		this.productModelName = productModelName;
	}
	@Column(name = "validateFnOnClient")
	public String getValidateFnOnClient() {
		return validateFnOnClient;
	}

	public void setValidateFnOnClient(String validateFnOnClient) {
		this.validateFnOnClient = validateFnOnClient;
	}
	@Column(name = "allowDuplicate")
	public Boolean getAllowDuplicate() {
		return allowDuplicate;
	}

	public void setAllowDuplicate(Boolean allowDuplicate) {
		this.allowDuplicate = allowDuplicate;
	}
	@Column(name = "validateFnOnServer")
	public String getValidateFnOnServer() {
		return validateFnOnServer;
	}

	public void setValidateFnOnServer(String validateFnOnServer) {
		this.validateFnOnServer = validateFnOnServer;
	}
	@Override
	public int compareTo(AssyProductModel o) {
		// TODO Auto-generated method stub
		return this.productModel.compareTo(o.productModel);
	}
}
