package tms.backend.domain;

// Generated Jun 11, 2014 11:25:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssyProductStation generated by hbm2java
 */
@Entity
@Table(name = "assy_product_station")
public class AssyProductStation implements java.io.Serializable {

	private Long id;
	private Long productType;
	private String station;
	private String productParams;
	private String productDefects;
	private Integer step;
	private String prerequisite;

	public AssyProductStation() {
	}

	public AssyProductStation(Long productModel, String station,
			String productParams, String productDefects, Integer step) {
		this.productType = productType;
		this.station = station;
		this.productParams = productParams;
		this.productDefects = productDefects;
		this.step = step;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "product_type")
	public Long getProductType() {
		return this.productType;
	}

	public void setProductType(Long productType) {
		this.productType = productType;
	}

	@Column(name = "station")
	public String getStation() {
		return this.station;
	}

	public void setStation(String station) {
		this.station = station;
	}

	@Column(name = "product_params", columnDefinition="TEXT")
	public String getProductParams() {
		return this.productParams;
	}

	public void setProductParams(String productParams) {
		this.productParams = productParams;
	}

	@Column(name = "product_defects", columnDefinition="TEXT")
	public String getProductDefects() {
		return this.productDefects;
	}

	public void setProductDefects(String productDefects) {
		this.productDefects = productDefects;
	}

	@Column(name = "step")
	public Integer getStep() {
		return this.step;
	}

	public void setStep(Integer step) {
		this.step = step;
	}
	@Column(name = "prerequisite")
	public String getPrerequisite() {
		return prerequisite;
	}

	public void setPrerequisite(String prerequisite) {
		this.prerequisite = prerequisite;
	}

}
