package tms.backend.domain;

// Generated Jun 11, 2014 11:25:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssyParameter generated by hbm2java
 */
@Entity
@Table(name = "assy_parameter")
public class AssyParameter implements java.io.Serializable {

	private Long id;
	private String parameterCode;
	private String parameterName;
	private Integer parameterSize;
	private Integer parameterColspan;
	private Integer parameterWidth;
	private String parameterValue;
	private Byte negativeValue;
	private String validateUrl;
	public AssyParameter() {
	}

	public AssyParameter(String parameterName) {
		this.parameterName = parameterName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "parameter_name", length = 255)
	public String getParameterName() {
		return this.parameterName;
	}

	public void setParameterName(String parameterName) {
		this.parameterName = parameterName;
	}
	@Column(name = "parameter_code", length = 20)
	public String getParameterCode() {
		return parameterCode;
	}

	public void setParameterCode(String parameterCode) {
		this.parameterCode = parameterCode;
	}
	@Column(name = "parameter_size")
	public Integer getParameterSize() {
		return parameterSize;
	}

	public void setParameterSize(Integer parameterSize) {
		this.parameterSize = parameterSize;
	}
	@Column(name = "parameter_colspan")
	public Integer getParameterColspan() {
		return parameterColspan;
	}

	public void setParameterColspan(Integer parameterColspan) {
		this.parameterColspan = parameterColspan;
	}
	@Column(name = "parameter_width")
	public Integer getParameterWidth() {
		return parameterWidth;
	}

	public void setParameterWidth(Integer parameterWidth) {
		this.parameterWidth = parameterWidth;
	}
	@Column(name = "parameter_value")
	public String getParameterValue() {
		return parameterValue;
	}

	public void setParameterValue(String parameterValue) {
		this.parameterValue = parameterValue;
	}
	@Column(name = "negative_value")
	public Byte getNegativeValue() {
		return negativeValue;
	}

	public void setNegativeValue(Byte negativeValue) {
		this.negativeValue = negativeValue;
	}
	@Column(name="validateUrl")
	public String getValidateUrl() {
		return validateUrl;
	}

	public void setValidateUrl(String validateUrl) {
		this.validateUrl = validateUrl;
	}

}
