package tms.backend.domain;

// Generated Jun 11, 2014 11:25:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssyProductType generated by hbm2java
 */
@Entity
@Table(name = "assy_product_type")
public class AssyProductType implements java.io.Serializable, Comparable<AssyProductType> {

	private Long id;
	private String productTypeCode;
	private String productTypeName;
	private String prefixFunction;
	private Integer serialSize;
	private String padding;
	private Byte autoresult;
	private Byte tester;
	private String reportUrl;

	public AssyProductType() {
	}

	public AssyProductType(String productTypeCode) {
		this.productTypeCode = productTypeCode;
	}

	public AssyProductType(String productTypeCode, String productTypeName) {
		this.productTypeCode = productTypeCode;
		this.productTypeName = productTypeName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "product_type_code", nullable = false)
	public String getProductTypeCode() {
		return this.productTypeCode;
	}

	public void setProductTypeCode(String productTypeCode) {
		this.productTypeCode = productTypeCode;
	}

	@Column(name = "product_type_name", columnDefinition="TEXT")
	public String getProductTypeName() {
		return this.productTypeName;
	}

	public void setProductTypeName(String productTypeName) {
		this.productTypeName = productTypeName;
	}
	@Column(name = "prefix_function", columnDefinition="TEXT")
	public String getPrefixFunction() {
		return prefixFunction;
	}

	public void setPrefixFunction(String prefixFunction) {
		this.prefixFunction = prefixFunction;
	}
	@Column(name = "serial_size")
	public Integer getSerialSize() {
		return serialSize;
	}

	public void setSerialSize(Integer serialSize) {
		this.serialSize = serialSize;
	}
	
	@Column(name = "padding")
	public String getPadding() {
		return padding;
	}

	public void setPadding(String padding) {
		this.padding = padding;
	}
	@Column(name = "autoresult")
	public Byte getAutoresult() {
		return autoresult;
	}

	public void setAutoresult(Byte autoresult) {
		this.autoresult = autoresult;
	}

	public String getReportUrl() {
		return reportUrl;
	}
	@Column(name = "reportUrl")
	public void setReportUrl(String reportUrl) {
		this.reportUrl = reportUrl;
	}
	@Column(name = "tester")	
	public Byte getTester() {
		return tester;
	}

	public void setTester(Byte tester) {
		this.tester = tester;
	}

	@Override
	public int compareTo(AssyProductType o) {
		// TODO Auto-generated method stub
		return this.productTypeCode.compareTo(o.productTypeCode);
	}


}
