package tms.backend.domain;

// Generated Oct 9, 2014 2:01:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AssyProductStationPrerequisite generated by hbm2java
 */
@Entity
@Table(name = "assy_product_station_prerequisite")
public class AssyProductStationPrerequisite implements java.io.Serializable {

	private Long id;
	private Date datetested;
	private Long productType;
	private Long productStation;
	private Long productModel;
	private Boolean active;
	private Boolean status;
	private String inputParameter;

	public AssyProductStationPrerequisite() {
	}

	public AssyProductStationPrerequisite(Date datetested, Long productType,
			Long productStation, Boolean active, Boolean status,
			String inputParameter) {
		this.datetested = datetested;
		this.productType = productType;
		this.productStation = productStation;
		this.active = active;
		this.status = status;
		this.inputParameter = inputParameter;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetested", length = 0)
	public Date getDatetested() {
		return this.datetested;
	}

	public void setDatetested(Date datetested) {
		this.datetested = datetested;
	}

	@Column(name = "product_type")
	public Long getProductType() {
		return this.productType;
	}

	public void setProductType(Long productType) {
		this.productType = productType;
	}

	@Column(name = "product_station")
	public Long getProductStation() {
		return this.productStation;
	}

	public void setProductStation(Long productStation) {
		this.productStation = productStation;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "input_parameter", columnDefinition="TEXT")
	public String getInputParameter() {
		return this.inputParameter;
	}

	public void setInputParameter(String inputParameter) {
		this.inputParameter = inputParameter;
	}
	@Column(name = "product_model")
	public Long getProductModel() {
		return productModel;
	}

	public void setProductModel(Long productModel) {
		this.productModel = productModel;
	}

}
