package tms.backend.domain;

// Generated Apr 18, 2016 11:37:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CourierShipment generated by hbm2java
 */
@Entity
@Table(name = "courier_shipment")
public class CourierShipment implements java.io.Serializable {

	private Long id;
	private String sender;
	private String department;
	private String shipmentCompany;
	private String shipmentContact;
	private String shipmentAddress;
	private String shipmentPurpose;
	
	private String paymentby;
	private String shipmentby;
	private Date documentDate;
	private String referenceNote;
	private String serviceType;
	private String packageQty;
	private Float weight;
	private Float length;
	private Float width;
	private Float height;
	private Boolean invoiced;
	private Boolean postedPs;
	private String psNo;
	private Boolean customs;
	
	private String approver;
	
	private String createdby;
	
	private String trackingNo;
	private String emailTo;
	private Byte status;
	
	
	public CourierShipment() {
	}

	public CourierShipment(String sender, String department,
			String shipmentCompany, String shipmentContact,
			String shipmentAddress, String paymentby, String shipmentby,
			Date documentDate, String referenceNote, String serviceType,
			String packageQty, Float weight, Float length, Float width,
			Float height, Boolean invoiced, Boolean postedPs, String approver,
			String psNo) {
		this.sender = sender;
		this.department = department;
		this.shipmentCompany = shipmentCompany;
		this.shipmentContact = shipmentContact;
		this.shipmentAddress = shipmentAddress;
		this.paymentby = paymentby;
		this.shipmentby = shipmentby;
		this.documentDate = documentDate;
		this.referenceNote = referenceNote;
		this.serviceType = serviceType;
		this.packageQty = packageQty;
		this.weight = weight;
		this.length = length;
		this.width = width;
		this.height = height;
		this.invoiced = invoiced;
		this.postedPs = postedPs;
		this.approver = approver;
		this.psNo = psNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "sender", length = 100)
	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	@Column(name = "department", length = 100)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "shipment_company", length = 100)
	public String getShipmentCompany() {
		return this.shipmentCompany;
	}

	public void setShipmentCompany(String shipmentCompany) {
		this.shipmentCompany = shipmentCompany;
	}

	@Column(name = "shipment_contact", length = 100)
	public String getShipmentContact() {
		return this.shipmentContact;
	}

	public void setShipmentContact(String shipmentContact) {
		this.shipmentContact = shipmentContact;
	}

	@Column(name = "shipment_address", length = 100)
	public String getShipmentAddress() {
		return this.shipmentAddress;
	}

	public void setShipmentAddress(String shipmentAddress) {
		this.shipmentAddress = shipmentAddress;
	}

	@Column(name = "paymentby", length = 20)
	public String getPaymentby() {
		return this.paymentby;
	}

	public void setPaymentby(String paymentby) {
		this.paymentby = paymentby;
	}

	@Column(name = "shipmentby", length = 20)
	public String getShipmentby() {
		return this.shipmentby;
	}

	public void setShipmentby(String shipmentby) {
		this.shipmentby = shipmentby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "document_date", length = 10)
	public Date getDocumentDate() {
		return this.documentDate;
	}

	public void setDocumentDate(Date documentDate) {
		this.documentDate = documentDate;
	}

	@Column(name = "reference_note", length = 200)
	public String getReferenceNote() {
		return this.referenceNote;
	}

	public void setReferenceNote(String referenceNote) {
		this.referenceNote = referenceNote;
	}

	@Column(name = "service_type", length = 20)
	public String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

	@Column(name = "package_qty", length = 20)
	public String getPackageQty() {
		return this.packageQty;
	}

	public void setPackageQty(String packageQty) {
		this.packageQty = packageQty;
	}

	@Column(name = "weight", precision = 9, scale = 3)
	public Float getWeight() {
		return this.weight;
	}

	public void setWeight(Float weight) {
		this.weight = weight;
	}

	@Column(name = "length", precision = 9, scale = 3)
	public Float getLength() {
		return this.length;
	}

	public void setLength(Float length) {
		this.length = length;
	}

	@Column(name = "width", precision = 9, scale = 3)
	public Float getWidth() {
		return this.width;
	}

	public void setWidth(Float width) {
		this.width = width;
	}

	@Column(name = "height", precision = 9, scale = 3)
	public Float getHeight() {
		return this.height;
	}

	public void setHeight(Float height) {
		this.height = height;
	}

	@Column(name = "invoiced")
	public Boolean getInvoiced() {
		return this.invoiced;
	}

	public void setInvoiced(Boolean invoiced) {
		this.invoiced = invoiced;
	}

	@Column(name = "posted_PS")
	public Boolean getPostedPs() {
		return this.postedPs;
	}

	public void setPostedPs(Boolean postedPs) {
		this.postedPs = postedPs;
	}

	@Column(name = "approver", length = 20)
	public String getApprover() {
		return this.approver;
	}

	public void setApprover(String approver) {
		this.approver = approver;
	}

	@Column(name = "PS_no", length = 100)
	public String getPsNo() {
		return this.psNo;
	}

	public void setPsNo(String psNo) {
		this.psNo = psNo;
	}
	@Column(name = "shipment_purpose", length = 200)
	public String getShipmentPurpose() {
		return shipmentPurpose;
	}

	public void setShipmentPurpose(String shipmentPurpose) {
		this.shipmentPurpose = shipmentPurpose;
	}
	@Column(name = "createdby", length = 100)
	public String getCreatedby() {
		return createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}
	@Column(name = "customs")
	public Boolean getCustoms() {
		return this.customs;
	}

	public void setCustoms(Boolean customs) {
		this.customs = customs;
	}
	@Column(name = "tracking_no")
	public String getTrackingNo() {
		return trackingNo;
	}

	public void setTrackingNo(String trackingNo) {
		this.trackingNo = trackingNo;
	}
	@Column(name = "email_to")
	public String getEmailTo() {
		return emailTo;
	}

	public void setEmailTo(String emailTo) {
		this.emailTo = emailTo;
	}
	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
