package tms.backend.domain;

// Generated Sep 12, 2013 8:08:12 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HrRecruitmentOrder generated by hbm2java
 */
@Entity
@Table(name = "hr_recruitment_order")
public class HrRecruitmentOrder implements java.io.Serializable {

	private Long id;
	private Date requestDate;
	private Integer departmentId;
	private Integer createdBy;
	private Integer approvedBy;
	private Date approvedDate;
	private Byte status;
	private byte priority;
	private Long recruitmentPosition;

	public HrRecruitmentOrder() {
	}

	public HrRecruitmentOrder(byte priority) {
		this.priority = priority;
	}

	public HrRecruitmentOrder(Date requestDate, Integer departmentId,
			Integer createdBy, Integer approvedBy, Date approvedDate,
			Byte status, byte priority, Long recruitmentPosition) {
		this.requestDate = requestDate;
		this.departmentId = departmentId;
		this.createdBy = createdBy;
		this.approvedBy = approvedBy;
		this.approvedDate = approvedDate;
		this.status = status;
		this.priority = priority;
		this.recruitmentPosition = recruitmentPosition;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "request_date", length = 0)
	public Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}

	@Column(name = "department_id")
	public Integer getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "approved_by")
	public Integer getApprovedBy() {
		return this.approvedBy;
	}

	public void setApprovedBy(Integer approvedBy) {
		this.approvedBy = approvedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "approved_date", length = 0)
	public Date getApprovedDate() {
		return this.approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "priority", nullable = false)
	public byte getPriority() {
		return this.priority;
	}

	public void setPriority(byte priority) {
		this.priority = priority;
	}

	@Column(name = "recruitment_position")
	public Long getRecruitmentPosition() {
		return this.recruitmentPosition;
	}

	public void setRecruitmentPosition(Long recruitmentPosition) {
		this.recruitmentPosition = recruitmentPosition;
	}

}
