package tms.backend.domain;

// Generated May 6, 2014 11:10:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InjMixedMaterialJournal generated by hbm2java
 */
@Entity
@Table(name = "inj_mixed_material_journal")
public class InjMixedMaterialJournal implements java.io.Serializable {

	private Long id;
	private Long idorder;
	private Date transdate;
	private String mixedMaterialCode;
	private String virginMaterialCode;
	private String virginMaterialName;
	private String regrindResinCode;
	private String regrindMaterialName;
	private Double regrindRate;
	private String color;
	private String moldCode;
	private String partCode;
	private String partName;
	private Double weight;
	private String operatorName;
	
	

	public InjMixedMaterialJournal() {
	}

	public InjMixedMaterialJournal(Date transdate, String mixedMaterialCode,
			String virginMaterialCode, String virginMaterialName,
			String regrindResinCode, String regrindMaterialName,
			Double regrindRate, String color, String moldCode, String partCode,
			String partName,Double weight,Long idorder ,String operatorName) {
		this.transdate = transdate;
		this.mixedMaterialCode = mixedMaterialCode;
		this.virginMaterialCode = virginMaterialCode;
		this.virginMaterialName = virginMaterialName;
		this.regrindResinCode = regrindResinCode;
		this.regrindMaterialName = regrindMaterialName;
		this.regrindRate = regrindRate;
		this.color = color;
		this.moldCode = moldCode;
		this.partCode = partCode;
		this.partName = partName;
		this.weight = weight;
		this.idorder = idorder;
		this.operatorName = operatorName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@Column(name = "idorder")
	public Long getIdOrder() {
		return this.idorder;
	}

	public void setIdOrder(Long idorder) {
		this.idorder = idorder;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "transdate", length = 0)
	public Date getTransdate() {
		return this.transdate;
	}

	public void setTransdate(Date transdate) {
		this.transdate = transdate;
	}

	@Column(name = "mixed_material_code", length = 20)
	public String getMixedMaterialCode() {
		return this.mixedMaterialCode;
	}

	public void setMixedMaterialCode(String mixedMaterialCode) {
		this.mixedMaterialCode = mixedMaterialCode;
	}

	@Column(name = "virgin_material_code", length = 20)
	public String getVirginMaterialCode() {
		return this.virginMaterialCode;
	}

	public void setVirginMaterialCode(String virginMaterialCode) {
		this.virginMaterialCode = virginMaterialCode;
	}

	@Column(name = "virgin_material_name")
	public String getVirginMaterialName() {
		return this.virginMaterialName;
	}

	public void setVirginMaterialName(String virginMaterialName) {
		this.virginMaterialName = virginMaterialName;
	}

	@Column(name = "regrind_resin_code", length = 20)
	public String getRegrindResinCode() {
		return this.regrindResinCode;
	}

	public void setRegrindResinCode(String regrindResinCode) {
		this.regrindResinCode = regrindResinCode;
	}

	@Column(name = "regrind_material_name")
	public String getRegrindMaterialName() {
		return this.regrindMaterialName;
	}

	public void setRegrindMaterialName(String regrindMaterialName) {
		this.regrindMaterialName = regrindMaterialName;
	}

	@Column(name = "regrind_rate", precision = 15, scale = 3)
	public Double getRegrindRate() {
		return this.regrindRate;
	}

	public void setRegrindRate(Double regrindRate) {
		this.regrindRate = regrindRate;
	}

	@Column(name = "color", length = 20)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "mold_code", length = 20)
	public String getMoldCode() {
		return this.moldCode;
	}

	public void setMoldCode(String moldCode) {
		this.moldCode = moldCode;
	}

	@Column(name = "part_code", length = 20)
	public String getPartCode() {
		return this.partCode;
	}

	public void setPartCode(String partCode) {
		this.partCode = partCode;
	}

	@Column(name = "part_name", length = 20)
	public String getPartName() {
		return this.partName;
	}

	public void setPartName(String partName) {
		this.partName = partName;
	}
	@Column(name = "weight", precision = 15, scale = 3)
	public Double getWeight() {
		return this.weight;
	}

	public void setWeight(Double weight) {
		this.weight = weight;
	}
	
	@Column(name = "operator_name")
	public String getOperatorName() {
		return operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}
}
