package tms.backend.domain;

// Generated May 6, 2014 11:10:29 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InjRegrindRate generated by hbm2java
 */
@Entity
@Table(name = "inj_regrind_rate", catalog = "enterprise_app")
public class InjRegrindRate implements java.io.Serializable {

	private Long id;
	private String productCode;
	private String productName;
	private String virginMaterialCode;
	private String virginMaterialName;
	private String masterbatchCode;
	private String masterbatchName;
	private String regrindResinCode;
	private String regrindResinName;
	private Double colorRate;
	private Double regrindRate;
	private Double constantScrap;
	
	private Double runnerWeight;
	private Double productWeight;
	
	public InjRegrindRate() {
	}

	public InjRegrindRate(String productCode, String productName,
			String virginMaterialCode, String virginMaterialName,
			String masterbatchCode, String masterbatchName,
			String regrindResinCode, String regrindResinName, Double colorRate,
			Double regrindRate, Double constantScrap, Double runnerWeight , Double productWeight) {
		this.productCode = productCode;
		this.productName = productName;
		this.virginMaterialCode = virginMaterialCode;
		this.virginMaterialName = virginMaterialName;
		this.masterbatchCode = masterbatchCode;
		this.masterbatchName = masterbatchName;
		this.regrindResinCode = regrindResinCode;
		this.regrindResinName = regrindResinName;
		this.colorRate = colorRate;
		this.regrindRate = regrindRate;
		this.constantScrap = constantScrap;
		this.runnerWeight = runnerWeight;
		this.productWeight = productWeight;
				
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "product_code", length = 20)
	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	@Column(name = "product_name")
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "virgin_material_code", length = 20)
	public String getVirginMaterialCode() {
		return this.virginMaterialCode;
	}

	public void setVirginMaterialCode(String virginMaterialCode) {
		this.virginMaterialCode = virginMaterialCode;
	}

	@Column(name = "virgin_material_name")
	public String getVirginMaterialName() {
		return this.virginMaterialName;
	}

	public void setVirginMaterialName(String virginMaterialName) {
		this.virginMaterialName = virginMaterialName;
	}

	@Column(name = "masterbatch_code", length = 20)
	public String getMasterbatchCode() {
		return this.masterbatchCode;
	}

	public void setMasterbatchCode(String masterbatchCode) {
		this.masterbatchCode = masterbatchCode;
	}

	@Column(name = "masterbatch_name")
	public String getMasterbatchName() {
		return this.masterbatchName;
	}

	public void setMasterbatchName(String masterbatchName) {
		this.masterbatchName = masterbatchName;
	}

	@Column(name = "regrind_resin_code", length = 20)
	public String getRegrindResinCode() {
		return this.regrindResinCode;
	}

	public void setRegrindResinCode(String regrindResinCode) {
		this.regrindResinCode = regrindResinCode;
	}

	@Column(name = "regrind_resin_name")
	public String getRegrindResinName() {
		return this.regrindResinName;
	}

	public void setRegrindResinName(String regrindResinName) {
		this.regrindResinName = regrindResinName;
	}

	@Column(name = "color_rate", precision = 15, scale = 3)
	public Double getColorRate() {
		return this.colorRate;
	}

	public void setColorRate(Double colorRate) {
		this.colorRate = colorRate;
	}

	@Column(name = "regrind_rate", precision = 15, scale = 3)
	public Double getRegrindRate() {
		return this.regrindRate;
	}

	public void setRegrindRate(Double regrindRate) {
		this.regrindRate = regrindRate;
	}
	@Column(name = "constant_scrap", precision = 15, scale = 3)
	public Double getConstantScrap() {
		return this.constantScrap;
	}

	public void setConstantScrap(Double constantscrap) {
		this.constantScrap = constantscrap;
	}
	
	@Column(name = "runner_weight", precision = 15, scale = 3)
	public Double getRunnerWeight() {
		return this.runnerWeight;
	}

	public void setRunnerWeight(Double runnerWeight) {
		this.runnerWeight = runnerWeight;
	}
	
	@Column(name = "product_weight", precision = 15, scale = 3)
	public Double getProductWeight() {
		return this.productWeight;
	}

	public void setProductWeight(Double productWeight) {
		this.productWeight = productWeight;
	}

}
