package tms.backend.domain;

// Generated May 6, 2014 11:10:29 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InjRegrindorder generated by hbm2java
 */
@Entity
//@Table(name = "inj_regrindorder", catalog = "enterprise_app")
@Table(name = "inj_manager_confirmation")
public class InjRegrindorder implements java.io.Serializable {
	 
	private Long id;
	private Long regrindShortage;
	private Date orderDate;
	private Byte orderStatus;
	
	private String moldCode;
	
	private String partCode;
	private String partName;
	
	private String color;
	private Double cavity;
	private Double runnerRatio;
	
	private Double theoreticalRegrindWeight;
	private Double preparedPartQty;
	
	private String virginMaterialCode;
	private String virginMaterialName;
	private Double virginMaterialWeight;
	
	private String regrindMaterialCode;
	private String regrindMaterialName;
	private Double regrindMaterialWeight;
	private Double regrindPercentage;
	
	private String masterbatchCode;
	private String masterbatchName;
	private Double masterbatchWeight;
	private Double masterbatchPercentage;
	
	private String mixedMaterialCode;
	private String mixedMaterialName;
	private Double mixedMaterialWeight;
	
	private String operatorName;
	
	
	public InjRegrindorder() {
	}

	public InjRegrindorder(Date orderDate, Byte orderStatus, String moldCode,
			String partCode, String partName, String color, Double cavity,
			Double runnerRatio, Double theoreticalRegrindWeight,
			Double preparedPartQty, String virginMaterialCode,
			String virginMaterialName, Double virginMaterialWeight,
			String regrindMaterialCode, String regrindMaterialName,
			Double regrindMaterialWeight, Double regrindPercentage,
			String masterbatchCode, String masterbatchName,
			Double materbatchWeight, Double materbatchPercentage,
			String mixedMaterialCode, String mixedMaterialName,
			Double mixedMaterialWeight, String operatorName,Long regrindShortage) {
		this.orderDate = orderDate;
		this.orderStatus = orderStatus;
		this.moldCode = moldCode;
		this.partCode = partCode;
		this.partName = partName;
		this.color = color;
		this.cavity = cavity;
		this.runnerRatio = runnerRatio;
		this.theoreticalRegrindWeight = theoreticalRegrindWeight;
		this.preparedPartQty = preparedPartQty;
		this.virginMaterialCode = virginMaterialCode;
		this.virginMaterialName = virginMaterialName;
		this.virginMaterialWeight = virginMaterialWeight;
		this.regrindMaterialCode = regrindMaterialCode;
		this.regrindMaterialName = regrindMaterialName;
		this.regrindMaterialWeight = regrindMaterialWeight;
		this.regrindPercentage = regrindPercentage;
		this.masterbatchCode = masterbatchCode;
		this.masterbatchName = masterbatchName;
		this.masterbatchWeight = materbatchWeight;
		this.masterbatchPercentage = materbatchPercentage;
		this.mixedMaterialCode = mixedMaterialCode;
		this.mixedMaterialName = mixedMaterialName;
		this.mixedMaterialWeight = mixedMaterialWeight;
		this.operatorName = operatorName;
		this.regrindShortage = regrindShortage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "regrind_shortage")
	public Long getRegrindShortage() {
		return this.regrindShortage;
	}

	public void setRegrindShortage(Long regrindShortage) {
		this.regrindShortage = regrindShortage;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "order_date", length = 0)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "order_status")
	public Byte getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(Byte orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "mold_code", length = 20)
	public String getMoldCode() {
		return this.moldCode;
	}

	public void setMoldCode(String moldCode) {
		this.moldCode = moldCode;
	}

	@Column(name = "part_code", length = 20)
	public String getPartCode() {
		return this.partCode;
	}

	public void setPartCode(String partCode) {
		this.partCode = partCode;
	}

	@Column(name = "part_name")
	public String getPartName() {
		return this.partName;
	}

	public void setPartName(String partName) {
		this.partName = partName;
	}

	@Column(name = "color", length = 25)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "cavity", precision = 15, scale = 3)
	public Double getCavity() {
		return this.cavity;
	}

	public void setCavity(Double cavity) {
		this.cavity = cavity;
	}

	@Column(name = "runner_ratio", precision = 15, scale = 3)
	public Double getRunnerRatio() {
		return this.runnerRatio;
	}

	public void setRunnerRatio(Double runnerRatio) {
		this.runnerRatio = runnerRatio;
	}

	@Column(name = "weight_regrind_theorically", precision = 15, scale = 3)
	public Double getTheoreticalRegrindWeight() {
		return this.theoreticalRegrindWeight;
	}

	public void setTheoreticalRegrindWeight(Double theoreticalRegrindWeight) {
		this.theoreticalRegrindWeight = theoreticalRegrindWeight;
	}

	@Column(name = "part_qty_prepared", precision = 15, scale = 3)
	public Double getPreparedPartQty() {
		return this.preparedPartQty;
	}

	public void setPreparedPartQty(Double preparedPartQty) {
		this.preparedPartQty = preparedPartQty;
	}

	@Column(name = "virgin_material_code", length = 20)
	public String getVirginMaterialCode() {
		return this.virginMaterialCode;
	}

	public void setVirginMaterialCode(String virginMaterialCode) {
		this.virginMaterialCode = virginMaterialCode;
	}

	@Column(name = "virgin_material_name")
	public String getVirginMaterialName() {
		return this.virginMaterialName;
	}

	public void setVirginMaterialName(String virginMaterialName) {
		this.virginMaterialName = virginMaterialName;
	}

	@Column(name = "virgin_material_weight", precision = 15, scale = 3)
	public Double getVirginMaterialWeight() {
		return this.virginMaterialWeight;
	}

	public void setVirginMaterialWeight(Double virginMaterialWeight) {
		this.virginMaterialWeight = virginMaterialWeight;
	}

	@Column(name = "regrind_material_code", length = 20)
	public String getRegrindMaterialCode() {
		return this.regrindMaterialCode;
	}

	public void setRegrindMaterialCode(String regrindMaterialCode) {
		this.regrindMaterialCode = regrindMaterialCode;
	}

	@Column(name = "regrind_material_name")
	public String getRegrindMaterialName() {
		return this.regrindMaterialName;
	}

	public void setRegrindMaterialName(String regrindMaterialName) {
		this.regrindMaterialName = regrindMaterialName;
	}

	@Column(name = "regrind_material_weight", precision = 15, scale = 3)
	public Double getRegrindMaterialWeight() {
		return this.regrindMaterialWeight;
	}

	public void setRegrindMaterialWeight(Double regrindMaterialWeight) {
		this.regrindMaterialWeight = regrindMaterialWeight;
	}

	@Column(name = "regrind_rate", precision = 15, scale = 3)
	public Double getRegrindPercentage() {
		return this.regrindPercentage;
	}

	public void setRegrindPercentage(Double regrindPercentage) {
		this.regrindPercentage = regrindPercentage;
	}

	@Column(name = "masterbatch_code", length = 20)
	public String getMasterbatchCode() {
		return this.masterbatchCode;
	}

	public void setMasterbatchCode(String masterbatchCode) {
		this.masterbatchCode = masterbatchCode;
	}

	@Column(name = "masterbatch_name")
	public String getMasterbatchName() {
		return this.masterbatchName;
	}

	public void setMasterbatchName(String masterbatchName) {
		this.masterbatchName = masterbatchName;
	}
					
	@Column(name = "masterbatch_weight", precision = 15, scale = 3)
	public Double getMasterbatchWeight() {
		return this.masterbatchWeight;
	}

	public void setMasterbatchWeight(Double masterbatchWeight) {
		this.masterbatchWeight = masterbatchWeight;
	}

	@Column(name = "masterbatch_rate", precision = 15, scale = 3)
	public Double getMasterbatchPercentage() {
		return this.masterbatchPercentage;
	}

	public void setMasterbatchPercentage(Double masterbatchPercentage) {
		this.masterbatchPercentage = masterbatchPercentage;
	}

	@Column(name = "mixed_material_code", length = 20)
	public String getMixedMaterialCode() {
		return this.mixedMaterialCode;
	}

	public void setMixedMaterialCode(String mixedMaterialCode) {
		this.mixedMaterialCode = mixedMaterialCode;
	}

	@Column(name = "mixed_material_name")
	public String getMixedMaterialName() {
		return this.mixedMaterialName;
	}

	public void setMixedMaterialName(String mixedMaterialName) {
		this.mixedMaterialName = mixedMaterialName;
	}
	
	@Column(name = "mixed_material_weight", precision = 15, scale = 3)
	public Double getMixedMaterialWeight() {
		return this.mixedMaterialWeight;
	}

	public void setMixedMaterialWeight(Double mixedMaterialWeight) {
		this.mixedMaterialWeight = mixedMaterialWeight;
	}

	@Column(name = "operator_name")
	public String getOperatorName() {
		return this.operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

}