package tms.backend.domain;

// Generated Oct 14, 2013 3:18:54 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PmProjectTask generated by hbm2java
 */
@Entity
@Table(name = "pm_project_task")
public class PmProjectTask implements java.io.Serializable {

	private Long id;
	private long projectId;
	private String projectTask;
	private Long parentTaskId;
	private Integer duration;
	private Byte leaf;
	private Date startDate;
	private Date endDate;
	private Long predecessor;
	private Byte sortorder;
	private Byte completedPercent;
	private String resourceList;

	public PmProjectTask() {
	}

	public PmProjectTask(long projectId) {
		this.projectId = projectId;
	}

	public PmProjectTask(long projectId, String projectTask, Long parentTaskId,
			Integer duration, Date startDate, Date endDate, Long predecessor,
			Byte sortorder, Byte completedPercent, String resourceList) {
		this.projectId = projectId;
		this.projectTask = projectTask;
		this.parentTaskId = parentTaskId;
		this.duration = duration;
		this.startDate = startDate;
		this.endDate = endDate;
		this.predecessor = predecessor;
		this.sortorder = sortorder;
		this.completedPercent = completedPercent;
		this.resourceList = resourceList;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "project_id", nullable = false)
	public long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(long projectId) {
		this.projectId = projectId;
	}

	@Column(name = "project_task", length = 200)
	public String getProjectTask() {
		return this.projectTask;
	}

	public void setProjectTask(String projectTask) {
		this.projectTask = projectTask;
	}

	@Column(name = "parent_task_id")
	public Long getParentTaskId() {
		return this.parentTaskId;
	}

	public void setParentTaskId(Long parentTaskId) {
		this.parentTaskId = parentTaskId;
	}

	@Column(name = "duration")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 0)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", length = 0)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "predecessor")
	public Long getPredecessor() {
		return this.predecessor;
	}

	public void setPredecessor(Long predecessor) {
		this.predecessor = predecessor;
	}
	@Column(name = "leaf")
	public Byte getLeaf() {
		return this.leaf;
	}

	public void setLeaf(Byte leaf) {
		this.leaf = leaf;
	}
	@Column(name = "sortorder")
	public Byte getSortorder() {
		return this.sortorder;
	}

	public void setSortorder(Byte sortorder) {
		this.sortorder = sortorder;
	}

	@Column(name = "completed_percent")
	public Byte getCompletedPercent() {
		return this.completedPercent;
	}

	public void setCompletedPercent(Byte completedPercent) {
		this.completedPercent = completedPercent;
	}

	@Column(name = "resource_list", length = 20)
	public String getResourceList() {
		return this.resourceList;
	}

	public void setResourceList(String resourceList) {
		this.resourceList = resourceList;
	}

}
