package tms.backend.domain;

// Generated Oct 14, 2013 3:18:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PmProject generated by hbm2java
 */
@Entity
@Table(name = "pm_project")
public class PmProject implements java.io.Serializable {

	private Long id;
	private String name;
	private Byte projectType;
	private Integer manager;
	private Long departmentId;
	private String departmentName;
	private Date startDate;
	private Date endDate;
	private Byte status;
	private String clientname;
	private String resourceList;

	public PmProject() {
	}

	public PmProject(String name, Byte projectType, Integer manager,
			Long departmentId, Date startDate, Date endDate, Byte status,
			String clientname, String resourceList) {
		this.name = name;
		this.projectType = projectType;
		this.manager = manager;
		this.departmentId = departmentId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.status = status;
		this.clientname = clientname;
		this.resourceList = resourceList;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}
	// name, getProjectType,getDepartmentId,getDepartmentId,getClientname,getManager,getStartDate,getEndDate,getStatus
	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "project_type")
	public Byte getProjectType() {
		return this.projectType;
	}

	public void setProjectType(Byte projectType) {
		this.projectType = projectType;
	}

	@Column(name = "manager")
	public Integer getManager() {
		return this.manager;
	}

	public void setManager(Integer manager) {
		this.manager = manager;
	}

	@Column(name = "department_id")
	public Long getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Long departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "department_name")
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}	
	
	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 0)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 0)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "clientname", length = 20)
	public String getClientname() {
		return this.clientname;
	}

	public void setClientname(String clientname) {
		this.clientname = clientname;
	}

	@Column(name = "resource_list", length = 20)
	public String getResourceList() {
		return this.resourceList;
	}

	public void setResourceList(String resourceList) {
		this.resourceList = resourceList;
	}

}
