package tms.backend.domain;

// Generated Oct 28, 2013 11:19:57 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PmResource generated by hbm2java
 */
@Entity
@Table(name = "pm_resource")
public class PmResource implements java.io.Serializable {

	private Long id;
	private String name;
	private Long employeeId;
	private String email;
	private Byte resourceType;
	private String memo;
	private Long projectId;

	public PmResource() {
	}

	public PmResource(String name, Long employeeId, String email,
			Byte resourceType, String memo, Long projectId) {
		this.name = name;
		this.employeeId = employeeId;
		this.email = email;
		this.resourceType = resourceType;
		this.memo = memo;
		this.projectId = projectId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "Name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "employee_id")
	public Long getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Long employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "email", length = 20)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "resource_type")
	public Byte getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(Byte resourceType) {
		this.resourceType = resourceType;
	}

	@Column(name = "memo")
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "project_id")
	public Long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

}
