package tms.backend.domain;

// Generated Aug 25, 2014 12:48:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QcInspectionTable generated by hbm2java
 */
@Entity
@Table(name = "qc_inspection_table")
public class QcInspectionTable implements java.io.Serializable {

	private Long id;
	private String productId;
	private String productName;
	private String orderNo;
	private Date transDate;
	private Byte transType;
	private Date inspectionDate;
	private Date receivedDate;
	private String vendor;
	private String vendorName;
	private Double transQty;
	private Double inspectionQty;
	private Integer critialDefect;
	private Integer majorDefect;
	private Integer minorDefect;
	private Byte status;
	private Byte isAccept;
	private String defectName;
	private String memo;

	public QcInspectionTable() {
	}

	public QcInspectionTable(String productId, String productName,
			Date transDate, Date inspectionDate, String vendor,
			Double transQty, Double inspectionQty, Integer critialDefect,
			Integer majorDefect, Integer minorDefect, Byte status,
			Byte isAccept, String defectName, String memo) {
		this.productId = productId;
		this.productName = productName;
		this.transDate = transDate;
		this.inspectionDate = inspectionDate;
		this.vendor = vendor;
		this.transQty = transQty;
		this.inspectionQty = inspectionQty;
		this.critialDefect = critialDefect;
		this.majorDefect = majorDefect;
		this.minorDefect = minorDefect;
		this.status = status;
		this.isAccept = isAccept;
		this.defectName = defectName;
		this.memo = memo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "product_id", length = 20)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "product_name")
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "trans_date", length = 0)
	public Date getTransDate() {
		return this.transDate;
	}

	public void setTransDate(Date transDate) {
		this.transDate = transDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "inspection_date", length = 0)
	public Date getInspectionDate() {
		return this.inspectionDate;
	}

	public void setInspectionDate(Date inspectionDate) {
		this.inspectionDate = inspectionDate;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "received_date", length = 0)
	public Date getReceivedDate() {
		return this.receivedDate;
	}

	public void setReceivedDate(Date receivedDate) {
		this.receivedDate = receivedDate;
	}
	@Column(name = "vendor", length = 20)
	public String getVendor() {
		return this.vendor;
	}

	public void setVendor(String vendor) {
		this.vendor = vendor;
	}
	@Column(name = "vendor_name", length = 255)
	public String getVendorName() {
		return this.vendorName;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}
	@Column(name = "trans_qty", precision = 15, scale = 3)
	public Double getTransQty() {
		return this.transQty;
	}

	public void setTransQty(Double transQty) {
		this.transQty = transQty;
	}
	@Column(name = "trans_type")
	public Byte getTransType() {
		return this.transType;
	}

	public void setTransType(Byte transType) {
		this.transType = transType;
	}
	
	@Column(name = "inspection_qty", precision = 15, scale = 3)
	public Double getInspectionQty() {
		return this.inspectionQty;
	}

	public void setInspectionQty(Double inspectionQty) {
		this.inspectionQty = inspectionQty;
	}

	@Column(name = "critial_defect")
	public Integer getCritialDefect() {
		return this.critialDefect;
	}

	public void setCritialDefect(Integer critialDefect) {
		this.critialDefect = critialDefect;
	}

	@Column(name = "major_defect")
	public Integer getMajorDefect() {
		return this.majorDefect;
	}

	public void setMajorDefect(Integer majorDefect) {
		this.majorDefect = majorDefect;
	}

	@Column(name = "minor_defect")
	public Integer getMinorDefect() {
		return this.minorDefect;
	}

	public void setMinorDefect(Integer minorDefect) {
		this.minorDefect = minorDefect;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "isAccept")
	public Byte getIsAccept() {
		return this.isAccept;
	}

	public void setIsAccept(Byte isAccept) {
		this.isAccept = isAccept;
	}

	@Column(name = "defect_name", columnDefinition="TEXT")
	public String getDefectName() {
		return this.defectName;
	}

	public void setDefectName(String defectName) {
		this.defectName = defectName;
	}

	@Column(name = "memo", columnDefinition="TEXT")
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}
	@Column(name = "order_no")
	public String getOrderNo() {
		return orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

}
