package tms.backend.domain;

// Generated Sep 2, 2014 2:40:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * QcInspectionDefect generated by hbm2java
 */
@Entity
@Table(name = "qc_inspection_defect")
public class QcInspectionDefect implements java.io.Serializable {

	private Long id;
	private String defectNameEn;
	private String defectNameVn;
	private String defectCode;
	private Byte status;

	public QcInspectionDefect() {
	}

	public QcInspectionDefect(String defectNameEn, String defectNameVn,
			String defectCode, Byte status) {
		this.defectNameEn = defectNameEn;
		this.defectNameVn = defectNameVn;
		this.defectCode = defectCode;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "defect_name_en",columnDefinition="TEXT")
	public String getDefectNameEn() {
		return this.defectNameEn;
	}

	public void setDefectNameEn(String defectNameEn) {
		this.defectNameEn = defectNameEn;
	}

	@Column(name = "defect_name_vn",columnDefinition="TEXT")
	public String getDefectNameVn() {
		return this.defectNameVn;
	}

	public void setDefectNameVn(String defectNameVn) {
		this.defectNameVn = defectNameVn;
	}

	@Column(name = "defect_code", columnDefinition="TEXT")
	public String getDefectCode() {
		return this.defectCode;
	}

	public void setDefectCode(String defectCode) {
		this.defectCode = defectCode;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
