package tms.backend.domain;

// Generated Aug 25, 2014 12:48:26 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * QcInspectionLine generated by hbm2java
 */
@Entity
@Table(name = "qc_inspection_line")
public class QcInspectionLine implements java.io.Serializable {

	private Long id;
	private Long inspectionId;
	private String defectCode;
	private String defectName;
	private Integer defectQty;
	private String memo;
	private String defectLevel;

	public QcInspectionLine() {
	}

	public QcInspectionLine(String defectLevel) {
		this.defectLevel = defectLevel;
	}

	public QcInspectionLine(Long inspectionId, String defectName,
			Integer defectQty, String memo, String defectLevel) {
		this.inspectionId = inspectionId;
		this.defectName = defectName;
		this.defectQty = defectQty;
		this.memo = memo;
		this.defectLevel = defectLevel;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "inspection_id")
	public Long getInspectionId() {
		return this.inspectionId;
	}

	public void setInspectionId(Long inspectionId) {
		this.inspectionId = inspectionId;
	}
	@Column(name = "defect_code", columnDefinition="TEXT")
	public String getDefectCode() {
		return this.defectCode;
	}

	public void setDefectCode(String defectCode) {
		this.defectCode = defectCode;
	}
	@Column(name = "defect_name", columnDefinition="TEXT")
	public String getDefectName() {
		return this.defectName;
	}

	public void setDefectName(String defectName) {
		this.defectName = defectName;
	}

	@Column(name = "defect_qty")
	public Integer getDefectQty() {
		return this.defectQty;
	}

	public void setDefectQty(Integer defectQty) {
		this.defectQty = defectQty;
	}

	@Column(name = "memo", columnDefinition="TEXT")
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "defect_level", columnDefinition="TEXT")
	public String getDefectLevel() {
		return this.defectLevel;
	}

	public void setDefectLevel(String defectLevel) {
		this.defectLevel = defectLevel;
	}

}
