package tms.backend.domain;

// Generated Nov 30, 2015 10:46:21 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WellingtonMotor generated by hbm2java
 */
@Entity
@Table(name = "wellington_motor")
public class WellingtonMotor implements java.io.Serializable, Comparable<WellingtonMotor> {

	private Long id;
	private String motorId;
	private String motorName;
	private Boolean active;
	private Integer maxQty;
	private Boolean hasFinalTest;

	public WellingtonMotor() {
	}

	public WellingtonMotor(String motorId, String motorName, Boolean active) {
		this.motorId = motorId;
		this.motorName = motorName;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "motor_id", length = 20)
	public String getMotorId() {
		return this.motorId;
	}

	public void setMotorId(String motorId) {
		this.motorId = motorId;
	}

	@Column(name = "motor_name")
	public String getMotorName() {
		return this.motorName;
	}

	public void setMotorName(String motorName) {
		this.motorName = motorName;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}
	@Column(name = "max_qty")
	public Integer getMaxQty() {
		return maxQty;
	}

	public void setMaxQty(Integer maxQty) {
		this.maxQty = maxQty;
	}
	@Column(name = "hasFinalTest")
	public Boolean getHasFinalTest() {
		return this.hasFinalTest;
	}

	public void setHasFinalTest(Boolean hasFinalTest) {
		this.hasFinalTest = hasFinalTest;
	}

	@Override
	public int compareTo(WellingtonMotor o) {
		// TODO Auto-generated method stub
		return this.motorId.compareTo(o.motorId);
	}
}
