package tms.backend.domain;

// Generated Jul 2, 2014 2:01:44 PM by Hibernate Tools 3.4.0.CR1

import java.io.BufferedReader;
import java.io.IOException;
import java.io.StringReader;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import tms.utils.StatusType;

/**
 * WellingtonTest generated by hbm2java
 */
@Entity
@Table(name = "wellington_test")
public class WellingtonTest implements java.io.Serializable {

	private Long id;
	private String motorSerial;
	private Byte status;
	private String batchno;
	private Date datetested;
	private String chesum;
	private String tester;
	private Integer limitNumber;
	private Integer limitVersion;
	private Integer limitRevision;
	private Double voltage;
	private String inputPowers;
	private Date datetimepacked;
	private String motorType;
	private Integer sequence;
	private String shipmentNo;
	private String customerOrder;
	private String customerRef;
	private String containerNo;
	private Boolean qctested;
	private Byte hipotResult;
	

	public WellingtonTest() {
	}

	public WellingtonTest(String motorSerial, Byte status, String batchno,
			Date datetested, String chesum, String tester, Integer limitNumber,
			Integer limitVersion, Integer limitRevision, Double voltage,
			String inputPowers, Date datetimepacked, String motorType,
			Integer sequence) {
		this.motorSerial = motorSerial;
		this.status = status;
		this.batchno = batchno;
		this.datetested = datetested;
		this.chesum = chesum;
		this.tester = tester;
		this.limitNumber = limitNumber;
		this.limitVersion = limitVersion;
		this.limitRevision = limitRevision;
		this.voltage = voltage;
		this.inputPowers = inputPowers;
		this.datetimepacked = datetimepacked;
		this.motorType = motorType;
		this.sequence = sequence;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "motor_serial")
	public String getMotorSerial() {
		return this.motorSerial;
	}

	public void setMotorSerial(String motorSerial) {
		this.motorSerial = motorSerial;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "batchno", length = 20)
	public String getBatchno() {
		return this.batchno;
	}

	public void setBatchno(String batchno) {
		this.batchno = batchno;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetested", length = 0)
	public Date getDatetested() {
		return this.datetested;
	}

	public void setDatetested(Date datetested) {
		this.datetested = datetested;
	}

	@Column(name = "chesum")
	public String getChesum() {
		return this.chesum;
	}

	public void setChesum(String chesum) {
		this.chesum = chesum;
	}

	@Column(name = "tester", length = 20)
	public String getTester() {
		return this.tester;
	}

	public void setTester(String tester) {
		this.tester = tester;
	}

	@Column(name = "limit_number")
	public Integer getLimitNumber() {
		return this.limitNumber;
	}

	public void setLimitNumber(Integer limitNumber) {
		this.limitNumber = limitNumber;
	}

	@Column(name = "limit_version")
	public Integer getLimitVersion() {
		return this.limitVersion;
	}

	public void setLimitVersion(Integer limitVersion) {
		this.limitVersion = limitVersion;
	}

	@Column(name = "limit_revision")
	public Integer getLimitRevision() {
		return this.limitRevision;
	}

	public void setLimitRevision(Integer limitRevision) {
		this.limitRevision = limitRevision;
	}

	@Column(name = "voltage", precision = 15, scale = 3)
	public Double getVoltage() {
		return this.voltage;
	}

	public void setVoltage(Double voltage) {
		this.voltage = voltage;
	}

	@Column(name = "input_powers", columnDefinition="TEXT")
	public String getInputPowers() {
		return this.inputPowers;
	}

	public void setInputPowers(String inputPowers) {
		this.inputPowers = inputPowers;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetimepacked", length = 0)
	public Date getDatetimepacked() {
		return this.datetimepacked;
	}

	public void setDatetimepacked(Date datetimepacked) {
		this.datetimepacked = datetimepacked;
	}

	@Column(name = "motor_type", length = 20)
	public String getMotorType() {
		return this.motorType;
	}

	public void setMotorType(String motorType) {
		this.motorType = motorType;
	}

	@Column(name = "sequence")
	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	@Override
	public boolean equals(Object v) {
		boolean retVal = false;

		if (v instanceof WellingtonTest) {
			WellingtonTest ptr = (WellingtonTest) v;
			retVal = (ptr.motorSerial.equals(this.motorSerial) && ptr.motorType.equals(this.motorType));
		}

		return retVal;
	}

	@Override
	public int hashCode() {
		int hash = 7;
		hash = 17 * hash + this.motorSerial.hashCode()+ this.motorType.hashCode();
		
		return hash;
	}
	@Override
	public String toString(){
		return this.motorSerial;
	}
	public String toCSVRow() throws IOException{
		SimpleDateFormat fmtDateTime = new SimpleDateFormat(
				"dd-MMM-yyyy hh:mm:ss");
		BufferedReader reader =null;
		if (this.inputPowers !=null){
			reader = new BufferedReader(new StringReader(this.inputPowers));	
		}
		
		
		return 	(this.motorSerial==null?",":this.motorSerial+",")+
				(this.motorType==null?",":this.motorType+",")+
				(this.datetimepacked==null?",":fmtDateTime.format(this.datetimepacked)+",")+
				(this.batchno==null?",":this.batchno+",")+
				(this.containerNo==null?",":this.containerNo+",")+
				(this.sequence==null?",":this.sequence+",")+
				(this.status==null?"":(this.status.intValue()==StatusType.FAILED.getValue()?"Fail,":"Pass,"))+
				(this.datetested==null?",":fmtDateTime.format(this.datetested)+",")+
				(this.chesum==null?",":this.chesum+",")+
				(this.tester==null?",":this.tester+",")+
				(this.qctested != null && this.qctested==true?"Yes,":"No,")+
				(this.limitNumber==null?",":this.limitNumber+",")+
				(this.limitVersion==null?",":this.limitVersion+",")+
				(this.limitRevision==null?",":this.limitRevision+",")+
				(this.voltage==null?",":this.voltage+",")+
				(reader==null?",":reader.readLine()+",");

	}
	@Column(name = "shipmentNo", length = 60)
	public String getShipmentNo() {
		return shipmentNo;
	}

	public void setShipmentNo(String shipmentNo) {
		this.shipmentNo = shipmentNo;
	}
	@Column(name = "customer_order")
	public String getCustomerOrder() {
		return this.customerOrder;
	}

	public void setCustomerOrder(String customerOrder) {
		this.customerOrder = customerOrder;
	}
	@Column(name = "customer_ref")
	public String getCustomerRef() {
		return this.customerRef;
	}

	public void setCustomerRef(String customerRef) {
		this.customerRef = customerRef;
	}
	@Column(name = "container_no")
	public String getContainerNo() {
		return this.containerNo;
	}

	public void setContainerNo(String containerNo) {
		this.containerNo = containerNo;
	}

	@Column(name = "qctested")
	public Boolean getQctested() {
		return qctested;
	}

	public void setQctested(Boolean qctested) {
		this.qctested = qctested;
	}
	@Column(name = "hipot_result")
	public Byte getHipotResult() {
		return this.hipotResult;
	}

	public void setHipotResult(Byte hipotResult) {
		this.hipotResult = status;
	}
}
