Ext.define('EAP.Model.Task', {
    extend: 'Ext.data.Model',
	 fields: [{name: 'id',type: 'int',useNull: true},
	          {name: 'taskname',type: 'string'},
	          {name: 'description',type: 'string'},
	          {name: 'requesterId',type: 'string'},
	          {name: 'requester',type: 'string'},
	          {name: 'requestdate'},
	          {name: 'targetdate'},
	          {name: 'confirmedDate'},
	          {name: 'plandate'},
	          {name: 'actualdate'},
	          {name: 'status',type: 'string'},
	          {name: 'priority',type: 'string'},
	          {name: 'department',type: 'string'},
	          {name: 'assigneeId',type: 'int'},
	          {name: 'assigneeEmail',type: 'string'},
	          {name: 'assigneeName',type: 'string'},
	          {name: 'scopeId',type: 'int'},
	          {name: 'statusId',type: 'int'},
	          {name: 'priorityId',type: 'int'},
	          {name: 'departmentId',type: 'int'},
	          {name: 'email',type: 'string'},
	          {name: 'assetId',type: 'int'},
	          {name: 'assetCode',type: 'string'},
	          {name: 'assetName',type: 'string'},
	          {name: 'requestType',type: 'string'},
	          {name: 'hasAttachmentFile',type: 'boolean'}],
    idProperty: 'id',
    validations: [{
        type: 'length',
        field: 'code',
        min: 1
    }]
});